-- Database Migration for Printing Shop Management System
-- Generated automatically

-- ==================== SCHEMA ====================
-- File: audit_logs.sql
-- audit logs table
-- create table if not exists audit_logs (
--   id bigint generated by default as identity primary key,
--   user_id bigint references users(id) on delete set null,
--   action text not null,
--   entity text,
--   entity_id bigint,
--   metadata jsonb,
--   created_at timestamp with time zone default now()
-- );


-- File: customers.sql
-- customers table
-- create table if not exists customers (
--   id bigint generated by default as identity primary key,
--   name text not null,
--   email text,
--   phone text,
--   address text,
--   company text,
--   notes text,
--   created_at timestamp with time zone default now(),
--   updated_at timestamp with time zone default now()
-- );


-- File: expenses.sql
-- expenses table
-- create table if not exists expenses (
--   id bigint generated by default as identity primary key,
--   category text not null,
--   description text,
--   amount numeric(12,2) not null,
--   paid_at date,
--   created_at timestamp with time zone default now(),
--   updated_at timestamp with time zone default now()
-- );


-- File: inventory.sql
-- inventory table
-- create table if not exists inventory (
--   id bigint generated by default as identity primary key,
--   name text not null,
--   category text,
--   stock_level integer not null default 0,
--   reorder_threshold integer not null default 10,
--   unit text,
--   supplier_id bigint references suppliers(id) on delete set null,
--   cost numeric(12,2) default 0,
--   created_at timestamp with time zone default now(),
--   updated_at timestamp with time zone default now()
-- );


-- File: invoices.sql
-- invoices table
-- create table if not exists invoices (
--   id bigint generated by default as identity primary key,
--   order_id bigint references orders(id) on delete set null,
--   customer_id bigint references customers(id) on delete set null,
--   invoice_number text not null unique,
--   status text not null default 'Unpaid',
--   total_amount numeric(12,2) not null default 0,
--   due_date date,
--   notes text,
--   created_at timestamp with time zone default now(),
--   updated_at timestamp with time zone default now()
-- );

-- create table if not exists invoice_items (
--   id bigint generated by default as identity primary key,
--   invoice_id bigint references invoices(id) on delete cascade,
--   description text,
--   quantity integer not null default 1,
--   unit_price numeric(12,2) not null default 0,
--   total_price numeric(12,2) generated always as (quantity * unit_price) stored,
--   created_at timestamp with time zone default now()
-- );


-- File: notifications.sql
-- notifications table
-- create table if not exists notifications (
--   id bigint generated by default as identity primary key,
--   user_id bigint references users(id) on delete set null,
--   title text not null,
--   message text not null,
--   read boolean default false,
--   type text,
--   data jsonb,
--   created_at timestamp with time zone default now()
-- );


-- File: orders.sql
-- orders table
-- create table if not exists orders (
--   id bigint generated by default as identity primary key,
--   customer_id bigint references customers(id) on delete set null,
--   reference text not null,
--   status text not null default 'Pending',
--   priority text default 'Normal',
--   due_date date,
--   total_amount numeric(12,2) default 0,
--   produced boolean default false,
--   notes text,
--   created_at timestamp with time zone default now(),
--   updated_at timestamp with time zone default now()
-- );

-- create table if not exists order_items (
--   id bigint generated by default as identity primary key,
--   order_id bigint references orders(id) on delete cascade,
--   product_id bigint references products(id) on delete set null,
--   description text,
--   quantity integer not null default 1,
--   unit_price numeric(12,2) not null default 0,
--   total_price numeric(12,2) generated always as (quantity * unit_price) stored,
--   created_at timestamp with time zone default now()
-- );


-- File: payments.sql
-- payments table
-- create table if not exists payments (
--   id bigint generated by default as identity primary key,
--   invoice_id bigint references invoices(id) on delete set null,
--   customer_id bigint references customers(id) on delete set null,
--   amount numeric(12,2) not null,
--   method text not null,
--   reference text,
--   status text not null default 'Completed',
--   paid_at timestamp with time zone default now(),
--   created_at timestamp with time zone default now()
-- );


-- File: products.sql
-- products table
-- create table if not exists products (
--   id bigint generated by default as identity primary key,
--   sku text unique not null,
--   name text not null,
--   description text,
--   unit_price numeric(12,2) not null default 0,
--   cost_price numeric(12,2) not null default 0,
--   category text,
--   created_at timestamp with time zone default now(),
--   updated_at timestamp with time zone default now()
-- );


-- -- File: roles.sql
-- -- roles table
-- create table if not exists roles (
--   id serial primary key,
--   name text unique not null,
--   description text,
--   created_at timestamp with time zone default now()
-- );

-- define role names for RBAC
insert into roles (name, description) values
('Super Admin','Full system access'),
('Manager','Manage customers, orders, inventory'),
('Cashier','Process sales and payments'),
('Designer','Review artwork and prepare jobs'),
('Printing Operator','Execute print production');


-- File: suppliers.sql
-- suppliers table
-- create table if not exists suppliers (
--   id bigint generated by default as identity primary key,
--   name text not null,
--   email text,
--   phone text,
--   address text,
--   notes text,
--   created_at timestamp with time zone default now(),
--   updated_at timestamp with time zone default now()
-- );


-- File: users.sql
-- users table
-- create table if not exists users (
--   id bigint generated by default as identity primary key,
--   name text not null,
--   email text unique not null,
--   password text not null,
--   role text not null default 'Cashier',
--   active boolean not null default true,
--   created_at timestamp with time zone default now(),
--   updated_at timestamp with time zone default now()
-- );


-- ==================== FUNCTIONS ====================
-- File: calculate_profit.sql
-- create or replace function calculate_profit()
-- returns table(total_revenue numeric, total_cost numeric, profit numeric)
-- language sql
-- as $$
--   select
--     coalesce(sum(i.total_amount),0) as total_revenue,
--     coalesce(sum(p.cost_price * oi.quantity),0) as total_cost,
--     coalesce(sum(i.total_amount),0) - coalesce(sum(p.cost_price * oi.quantity),0) as profit
--   from invoices i
--   left join order_items oi on oi.order_id = i.order_id
--   left join products p on p.id = oi.product_id;
-- $$;


-- File: generate_invoice.sql
-- create or replace function generate_invoice(order_id bigint)
-- returns table(invoice_id bigint, invoice_number text, total_amount numeric)
-- language plpgsql
-- as $$
-- begin
--   insert into invoices (order_id, customer_id, invoice_number, status, total_amount, due_date)
--   select o.id, o.customer_id, concat('INV-', to_char(now(), 'YYYYMMDD'), '-', o.id), 'Unpaid', o.total_amount, now()::date + 14
--   from orders o
--   where o.id = order_id
--   returning id, invoice_number, total_amount into invoice_id, invoice_number, total_amount;
--   return next;
-- end;
-- $$;


-- File: inventory_alert.sql
-- create or replace function inventory_alert()
-- returns trigger
-- language plpgsql
-- as $$
-- begin
--   if new.stock_level <= new.reorder_threshold then
--     insert into notifications (user_id, title, message, type, data)
--     values (null, 'Low stock alert', concat(new.name, ' stock is below threshold.'), 'alert', jsonb_build_object('inventory_id', new.id, 'stock_level', new.stock_level));
--   end if;
--   return new;
-- end;
-- $$;


-- ==================== TRIGGERS ====================
-- File: audit_log.sql
-- create or replace function audit_log_trigger()
-- returns trigger
-- language plpgsql
-- as $$
-- begin
--   insert into audit_logs (user_id, action, entity, entity_id, metadata)
--   values (current_setting('app.current_user_id', true)::bigint, tg_op, TG_TABLE_NAME, coalesce(new.id, old.id), row_to_json(new));
--   return new;
-- end;
-- $$;

-- create trigger audit_log_insert
-- after insert on orders
-- for each row execute function audit_log_trigger();

-- create trigger audit_log_update
-- after update on orders
-- for each row execute function audit_log_trigger();


-- File: update_stock.sql
-- create trigger inventory_stock_alert
-- after update on inventory
-- for each row execute function inventory_alert();


-- File: update_timestamps.sql
-- create or replace function update_timestamp()
-- returns trigger
-- language plpgsql
-- as $$
-- begin
--   new.updated_at = now();
--   return new;
-- end;
-- $$;

-- create trigger users_update_timestamp
-- before update on users
-- for each row execute function update_timestamp();

-- create trigger customers_update_timestamp
-- before update on customers
-- for each row execute function update_timestamp();

-- create trigger orders_update_timestamp
-- before update on orders
-- for each row execute function update_timestamp();

-- create trigger products_update_timestamp
-- before update on products
-- for each row execute function update_timestamp();

-- create trigger inventory_update_timestamp
-- before update on inventory
-- for each row execute function update_timestamp();

-- create trigger invoices_update_timestamp
-- before update on invoices
-- for each row execute function update_timestamp();

-- create trigger payments_update_timestamp
-- before update on payments
-- for each row execute function update_timestamp();


-- ==================== VIEWS ====================
-- File: customer_statistics.sql
-- create or replace view customer_statistics as
-- select
--   c.id as customer_id,
--   c.name,
--   c.email,
--   count(distinct o.id) as total_orders,
--   coalesce(sum(i.total_amount),0) as total_spent
-- from customers c
-- left join orders o on o.customer_id = c.id
-- left join invoices i on i.customer_id = c.id
-- group by c.id, c.name, c.email;


-- File: inventory_status.sql
-- create or replace view inventory_status as
-- select
--   i.id,
--   i.name,
--   i.category,
--   i.stock_level,
--   i.reorder_threshold,
--   case when i.stock_level <= i.reorder_threshold then 'Low' else 'Healthy' end as status
-- from inventory i;


-- File: sales_summary.sql
-- create or replace view sales_summary as
-- select
--   date_trunc('day', i.created_at) as period,
--   sum(i.total_amount) as total_sales,
--   count(distinct i.id) as invoices_count
-- from invoices i
-- group by date_trunc('day', i.created_at)
-- order by period desc;


