-- audit logs table
create table if not exists audit_logs (
  id bigint generated by default as identity primary key,
  user_id bigint references users(id) on delete set null,
  action text not null,
  entity text,
  entity_id bigint,
  metadata jsonb,
  created_at timestamp with time zone default now()
);
