-- expenses table
create table if not exists expenses (
  id bigint generated by default as identity primary key,
  category text not null,
  description text,
  amount numeric(12,2) not null,
  paid_at date,
  created_at timestamp with time zone default now(),
  updated_at timestamp with time zone default now()
);
