-- inventory table
create table if not exists inventory (
  id bigint generated by default as identity primary key,
  name text not null,
  category text,
  stock_level integer not null default 0,
  reorder_threshold integer not null default 10,
  unit text,
  supplier_id bigint references suppliers(id) on delete set null,
  cost numeric(12,2) default 0,
  created_at timestamp with time zone default now(),
  updated_at timestamp with time zone default now()
);
