-- invoices table
create table if not exists invoices (
  id bigint generated by default as identity primary key,
  order_id bigint references orders(id) on delete set null,
  customer_id bigint references customers(id) on delete set null,
  invoice_number text not null unique,
  status text not null default 'Unpaid',
  total_amount numeric(12,2) not null default 0,
  due_date date,
  notes text,
  created_at timestamp with time zone default now(),
  updated_at timestamp with time zone default now()
);

create table if not exists invoice_items (
  id bigint generated by default as identity primary key,
  invoice_id bigint references invoices(id) on delete cascade,
  description text,
  quantity integer not null default 1,
  unit_price numeric(12,2) not null default 0,
  total_price numeric(12,2) generated always as (quantity * unit_price) stored,
  created_at timestamp with time zone default now()
);
