-- notifications table
create table if not exists notifications (
  id bigint generated by default as identity primary key,
  user_id bigint references users(id) on delete set null,
  title text not null,
  message text not null,
  read boolean default false,
  type text,
  data jsonb,
  created_at timestamp with time zone default now()
);
