-- orders table
create table if not exists orders (
  id bigint generated by default as identity primary key,
  customer_id bigint references customers(id) on delete set null,
  reference text not null,
  status text not null default 'Pending',
  priority text default 'Normal',
  due_date date,
  total_amount numeric(12,2) default 0,
  produced boolean default false,
  notes text,
  created_at timestamp with time zone default now(),
  updated_at timestamp with time zone default now()
);

create table if not exists order_items (
  id bigint generated by default as identity primary key,
  order_id bigint references orders(id) on delete cascade,
  product_id bigint references products(id) on delete set null,
  description text,
  quantity integer not null default 1,
  unit_price numeric(12,2) not null default 0,
  total_price numeric(12,2) generated always as (quantity * unit_price) stored,
  created_at timestamp with time zone default now()
);
