-- payments table
create table if not exists payments (
  id bigint generated by default as identity primary key,
  invoice_id bigint references invoices(id) on delete set null,
  customer_id bigint references customers(id) on delete set null,
  amount numeric(12,2) not null,
  method text not null,
  reference text,
  status text not null default 'Completed',
  paid_at timestamp with time zone default now(),
  created_at timestamp with time zone default now()
);
