-- products table
create table if not exists products (
  id bigint generated by default as identity primary key,
  sku text unique not null,
  name text not null,
  description text,
  unit_price numeric(12,2) not null default 0,
  cost_price numeric(12,2) not null default 0,
  category text,
  created_at timestamp with time zone default now(),
  updated_at timestamp with time zone default now()
);
