-- suppliers table
create table if not exists suppliers (
  id bigint generated by default as identity primary key,
  name text not null,
  email text,
  phone text,
  address text,
  notes text,
  created_at timestamp with time zone default now(),
  updated_at timestamp with time zone default now()
);
