-- users table
create table if not exists users (
  id bigint generated by default as identity primary key,
  name text not null,
  email text unique not null,
  password text not null,
  role text not null default 'Cashier',
  active boolean not null default true,
  created_at timestamp with time zone default now(),
  updated_at timestamp with time zone default now()
);
